# Generated by Django 3.2 on 2021-05-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_post_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
