# Generated by Django 3.2 on 2021-05-03 20:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_post_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='productDetails',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
